"""Initial database schema based on spec

Revision ID: 689a2b798a79
Revises: 
Create Date: 2025-12-01 13:30:13.466664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689a2b798a79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cares_id'), table_name='cares')
    op.drop_index(op.f('ix_cares_user_id'), table_name='cares')
    op.drop_table('cares')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_defaults_id'), table_name='user_defaults')
    op.drop_table('user_defaults')
    op.drop_table('BloodPressure')
    op.drop_table('BloodSugar')
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_id'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_table('drug_used')
    op.drop_table('News')
    op.drop_table('a1c_records')
    op.drop_table('Weight')
    op.drop_table('care_info')
    op.drop_table('measurement_records')
    op.drop_index(op.f('ix_blood_sugar_records_id'), table_name='blood_sugar_records')
    op.drop_index(op.f('ix_blood_sugar_records_user_id'), table_name='blood_sugar_records')
    op.drop_table('blood_sugar_records')
    op.drop_table('medical_info')
    op.drop_index(op.f('ix_blood_pressure_records_id'), table_name='blood_pressure_records')
    op.drop_index(op.f('ix_blood_pressure_records_user_id'), table_name='blood_pressure_records')
    op.drop_table('blood_pressure_records')
    op.drop_table('Share')
    op.drop_table('Friendship')
    op.drop_table('UserProfile')
    op.drop_table('DiaryDiet')
    op.drop_table('user_settings')
    op.drop_table('friend_requests')
    op.drop_table('UserAuth')
    op.drop_index(op.f('ix_upload_records_id'), table_name='upload_records')
    op.drop_index(op.f('ix_upload_records_user_id'), table_name='upload_records')
    op.drop_table('upload_records')
    op.drop_index(op.f('ix_weight_records_id'), table_name='weight_records')
    op.drop_index(op.f('ix_weight_records_user_id'), table_name='weight_records')
    op.drop_table('weight_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('bmi', sa.FLOAT(), nullable=True),
    sa.Column('body_fat', sa.FLOAT(), nullable=True),
    sa.Column('measured_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_records_user_id'), 'weight_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_weight_records_id'), 'weight_records', ['id'], unique=False)
    op.create_table('upload_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('record_type', sa.VARCHAR(), nullable=False),
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_records_user_id'), 'upload_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_upload_records_id'), 'upload_records', ['id'], unique=False)
    op.create_table('UserAuth',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('account', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=True),
    sa.Column('privacy_policy', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=True),
    sa.Column('must_change_password', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=True),
    sa.Column('login_token', sa.TEXT(), nullable=True),
    sa.Column('password_reset_token', sa.TEXT(), nullable=True),
    sa.Column('token_expire_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('relation_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('read', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['relation_id'], ['UserAuth.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('after_recording', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('no_recording_for_a_day', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('notification_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('theme', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('DiaryDiet',
    sa.Column('id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('meal', sa.INTEGER(), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=100), nullable=True),
    sa.Column('image', sa.INTEGER(), nullable=True),
    sa.Column('lat', sa.REAL(), nullable=True),
    sa.Column('lng', sa.REAL(), nullable=True),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserProfile',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('gender', sa.BOOLEAN(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('invitCode', sa.TEXT(), nullable=True),
    sa.Column('badge', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Friendship',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('friend_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['UserAuth.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Share',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('fid', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data_type', sa.INTEGER(), nullable=False),
    sa.Column('relation_type', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('shared_with_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_pressure_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('systolic', sa.INTEGER(), nullable=False),
    sa.Column('diastolic', sa.INTEGER(), nullable=False),
    sa.Column('pulse', sa.INTEGER(), nullable=True),
    sa.Column('measured_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_pressure_records_user_id'), 'blood_pressure_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_blood_pressure_records_id'), 'blood_pressure_records', ['id'], unique=False)
    op.create_table('medical_info',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('oad', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('insulin', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('anti_hypertensives', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('diabetes_type', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('blood_sugar_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('sugar_level', sa.INTEGER(), nullable=False),
    sa.Column('meal_time', sa.INTEGER(), nullable=True),
    sa.Column('measured_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_sugar_records_user_id'), 'blood_sugar_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_blood_sugar_records_id'), 'blood_sugar_records', ['id'], unique=False)
    op.create_table('measurement_records',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('record_type', sa.INTEGER(), nullable=False),
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_info',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=True),
    sa.Column('reply_id', sa.INTEGER(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Weight',
    sa.Column('id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('body_fat', sa.FLOAT(), nullable=True),
    sa.Column('bmi', sa.FLOAT(), nullable=True),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('a1c_records',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('a1c', sa.VARCHAR(length=50), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('News',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('member_id', sa.INTEGER(), nullable=True),
    sa.Column('group', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('pushed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_used',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_used', sa.BOOLEAN(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_id'), 'verification_codes', ['id'], unique=False)
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    op.create_table('BloodSugar',
    sa.Column('id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('sugar', sa.INTEGER(), nullable=False),
    sa.Column('timeperiod', sa.INTEGER(), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BloodPressure',
    sa.Column('id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('systolic', sa.FLOAT(), nullable=False),
    sa.Column('diastolic', sa.FLOAT(), nullable=False),
    sa.Column('pulse', sa.FLOAT(), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserAuth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_defaults',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('sugar_morning_max', sa.INTEGER(), nullable=True),
    sa.Column('sugar_morning_min', sa.INTEGER(), nullable=True),
    sa.Column('sugar_afternoon_max', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('sugar_afternoon_min', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('sugar_evening_max', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('sugar_evening_min', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_defaults_id'), 'user_defaults', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('fcm_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('birthday', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.INTEGER(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('avatar', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('fb_id', sa.VARCHAR(), nullable=True),
    sa.Column('google_id', sa.VARCHAR(), nullable=True),
    sa.Column('apple_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cares',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=True),
    sa.Column('reply_id', sa.INTEGER(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('viewed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cares_user_id'), 'cares', ['user_id'], unique=False)
    op.create_index(op.f('ix_cares_id'), 'cares', ['id'], unique=False)
    # ### end Alembic commands ###
