"""Add Login table

Revision ID: 7d60e40cbb6c
Revises: d6cc8a6bdcad
Create Date: 2025-10-21 14:08:48.796535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d60e40cbb6c'
down_revision: Union[str, Sequence[str], None] = 'd6cc8a6bdcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
